### ISSUE TITLE
Is transparency possible?

### ISSUE THREAD

**Issue by alphaChris** [jaydenseric/Purty-Picker#5]
We really like this color picker and would like to add a transparency picker. 
This should then add transparency to the selected color. 
Is it possible that such a function will be included in the master by default?

**Comment by jaydenseric** [comment]
Hi @alphaChris , glad to hear you like it :)

I have not been improving this color picker for quite a few years because I actually don't use jQuery or Zepto anymore in my projects. I can't remember my original thoughts about adding transparency features, but it does sound like a good idea. If I was to resurrect this package I would completely retool it for 2023, drop the jQuery dependency, and publish it to npm. I don't think this effort is worth it though because now we have a native HTML input for selecting colors:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

It's browser support is not too bad:

https://caniuse.com/input-color

Closing this feature request issue as not planned, not because it isn't a good idea but just because I don't plan to work on it. If that situation changes I will reopen :)
